spring:
  application:
    name: movieon
  lifecycle:
    timeout-per-shutdown-phase: 20s
  config:
    import: classpath:notifications.yml, classpath:payments.yml, classpath:accounts.yml

server:
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true
