spring:
  application:
    name: movieon
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true
