spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  config:
    import: classpath:notifications.yml, classpath:payments.yml, classpath:accounts.yml
  flyway:
    placeholder-replacement: false


logging:
  level:
    kr.flab.movieon: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.transaction: trace
    org.springframework.orm: trace
