spring:
  application:
    name: movieon
  lifecycle:
    timeout-per-shutdown-phase: 20s
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration

server:
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true
