spring:
  redis:
    host: localhost
    password:
    port: 6379
  mail:
    host: smtp.gmail.com
    username: [email]
    password: [password]
    port: 587
    properties:
      mail.smtp:
        auth: true
        timeout: 5000
        starttls:
          enable: true
  flyway:
    placeholder-replacement: false
  datasource:
    url: jdbc:mysql://localhost:3306/movieon
    username: joyful
    password: 12345678!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

server:
  port: 8080

app:
  url: 'http://localhost:${server.port}'


logging:
  level:
    kr.flab.movieon: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.transaction: trace
    org.springframework.orm: trace
