create table account
(
    id                             bigint generated by default as identity,
    email                          varchar(255) not null,
    email_check_token              varchar(255),
    email_check_token_generated_at timestamp,
    email_verified                 boolean      not null,
    joined_at                      timestamp,
    last_modified_at               timestamp,
    password                       varchar(255) not null,
    username                       varchar(255),
    withdraw                       boolean      not null,
    withdrawal_at                  timestamp,
    primary key (id)
)

create table account_roles
(
    account_id bigint not null,
    roles      varchar(255)
)

create table category
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
)

create table item
(
    id             bigint generated by default as identity,
    available_days binary(255),
    base_price     decimal(19, 2),
    created_at     timestamp,
    modified_at    timestamp,
    name           varchar(255),
    product_id     bigint,
    type           varchar(255),
    primary key (id)
)

create table item_options
(
    item_id     bigint not null,
    option_name varchar(255),
    sales_price decimal(19, 2)
)

create table notification
(
    notification_type varchar(31)  not null,
    id                bigint generated by default as identity,
    created_at        timestamp,
    message           varchar(255) not null,
    account_id        bigint,
    email             varchar(255),
    title             varchar(255),
    primary key (id)
)

create table notification_group
(
    id       bigint generated by default as identity,
    disabled boolean not null,
    type     varchar(255),
    primary key (id)
)

create table notification_group_options
(
    notification_group_id bigint  not null,
    disabled              boolean not null,
    type                  varchar(255)
)

create table notification_setting
(
    id          bigint generated by default as identity,
    created_at  timestamp,
    modified_at timestamp,
    account_id  bigint,
    primary key (id)
)

create table notification_setting_groups
(
    notification_setting_id bigint not null,
    groups_id               bigint not null,
    primary key (notification_setting_id, groups_id)
)

create table notification_template
(
    id          bigint generated by default as identity,
    contents    TEXT         not null,
    created_at  timestamp,
    modified_at timestamp,
    name        varchar(255) not null,
    type        varchar(255),
    title       varchar(255),
    primary key (id)
)

create table order_line_item
(
    id         bigint generated by default as identity,
    base_price decimal(19, 2),
    item_id    bigint,
    name       varchar(255),
    primary key (id)
)

create table order_line_item_options
(
    order_line_item_id bigint not null,
    option_name        varchar(255),
    sales_price        decimal(19, 2)
)

create table orders
(
    id           bigint generated by default as identity,
    completed_at timestamp,
    created_at   timestamp,
    account_id   bigint         not null,
    modified_at  timestamp,
    order_id     varchar(255)   not null,
    pay_method   varchar(255)   not null,
    status       varchar(255),
    total_amount decimal(19, 2) not null,
    use_of_point decimal(19, 2) not null,
    primary key (id)
)

create table orders_line_items
(
    order_id      bigint not null,
    line_items_id bigint not null
)

create table product
(
    id                bigint generated by default as identity,
    actors            varchar(255),
    available_devices varchar(255),
    director          varchar(255),
    drm               boolean not null,
    provided_quality  varchar(255),
    rate              integer,
    release           date,
    running_time      bigint,
    created_at        timestamp,
    description       varchar(255),
    modified_at       timestamp,
    name              varchar(255),
    thumbnails        varchar(255),
    category_id       bigint,
    primary key (id)
)

create table product_images
(
    product_id bigint not null,
    images     varchar(255)
)

create table refresh_token_info
(
    id                bigint generated by default as identity,
    created_at        timestamp,
    expired           boolean not null,
    refresh_token_jti varchar(255),
    primary key (id)
)

create table toss_payments
(
    id                      bigint generated by default as identity,
    cancel_amount           integer,
    cancel_reason           varchar(255),
    canceled_at             timestamp,
    refundable_amount       integer,
    tax_free_amount_cancel  integer,
    acquire_status          varchar(255),
    approve_no              varchar(255),
    card_type               varchar(255),
    company                 varchar(255),
    installment_plan_months integer,
    is_interest_free        boolean not null,
    number                  varchar(255),
    owner_type              varchar(255),
    receipt_url             varchar(255),
    use_card_point          boolean not null,
    created_at              timestamp,
    approved_at             timestamp,
    balance_amount          integer,
    mid                     varchar(255),
    order_id                varchar(255),
    order_name              varchar(255),
    payment_key             varchar(255),
    requested_at            timestamp,
    status                  varchar(255),
    supplied_amount         integer,
    tax_free_amount         integer,
    total_amount            integer,
    transaction_key         varchar(255),
    type                    varchar(255),
    vat                     integer,
    version                 varchar(255),
    modified_at             timestamp,
    pay_method              varchar(255),
    primary key (id)
)

alter table account
    add constraint UK_q0uja26qgu1atulenwup9rxyr unique (email)

alter table notification_setting_groups
    add constraint UK_nn6dyxtmimv4oyme792k3i7kv unique (groups_id)

alter table notification_template
    add constraint UK_2hkvijod8b8id26qum26cstr unique (name)

alter table orders
    add constraint UK_hmsk25beh6atojvle1xuymjj0 unique (order_id)

alter table orders_line_items
    add constraint UK_frp259x5fvoyc35w6dd1rnj84 unique (line_items_id)

alter table account_roles
    add constraint FKtp61eta5i06bug3w1qr6286uf
        foreign key (account_id)
            references account

alter table item_options
    add constraint FKa1xrbrsl59scj2oab4gs5l1cb
        foreign key (item_id)
            references item

alter table notification_group_options
    add constraint FKi7s3e93ji16s2d5gbapqhmy6m
        foreign key (notification_group_id)
            references notification_group

alter table notification_setting_groups
    add constraint FK2l6xrq8l8g8x3aqugrtls8tug
        foreign key (groups_id)
            references notification_group

alter table notification_setting_groups
    add constraint FKbyycim66xnjyjpgwsbwvd8atg
        foreign key (notification_setting_id)
            references notification_setting

alter table order_line_item_options
    add constraint FK5qg2lqribwg0j62i4m1xj2fr1
        foreign key (order_line_item_id)
            references order_line_item

alter table orders_line_items
    add constraint FKsy09cay6jwmyk4jrh9r7y9h2x
        foreign key (line_items_id)
            references order_line_item

alter table orders_line_items
    add constraint FKemt0roi7rjadfixob26kp6u4q
        foreign key (order_id)
            references orders

alter table product
    add constraint FK1mtsbur82frn64de7balymq9s
        foreign key (category_id)
            references category

alter table product_images
    add constraint FKi8jnqq05sk5nkma3pfp3ylqrt
        foreign key (product_id)
            references product
